import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import { AuthKitProvider } from "@workos-inc/authkit-nextjs/components";
import "./globals.css";
import Header from "@/components/header";
import { withAuth } from "@workos-inc/authkit-nextjs";
const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await withAuth({ ensureSignedIn: true });

  return (
    <html lang="en">
      <body className={`${ibmPlexSans.variable} antialiased`}>
        <Header user={user} />
        <AuthKitProvider>{children}</AuthKitProvider>
      </body>
    </html>
  );
}
